version: "3"
networks:
  demo-network:
    driver: bridge

services:
    redis:
        container_name: redis
        image: redis
        hostname: redis
        restart: always
        networks:
          - demo-network
        ports:
          - "6379:6379"
        volumes:
          - ./data/redis-data:/data